[2025-09-11 08:49:26,575] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T08:49:25.020713+00:00 [queued]>
[2025-09-11 08:49:26,582] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T08:49:25.020713+00:00 [queued]>
[2025-09-11 08:49:26,583] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 08:49:26,584] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-09-11 08:49:26,585] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 08:49:26,595] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): move_images> on 2025-09-11 08:49:25.020713+00:00
[2025-09-11 08:49:26,599] {standard_task_runner.py:52} INFO - Started process 697 to run task
[2025-09-11 08:49:26,601] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-11T08:49:25.020713+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpgso_m1d5', '--error-file', '/tmp/tmppj8zvyl_']
[2025-09-11 08:49:26,602] {standard_task_runner.py:80} INFO - Job 23: Subtask move_images
[2025-09-11 08:49:26,635] {task_command.py:370} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T08:49:25.020713+00:00 [running]> on host 17d4e251db5b
[2025-09-11 08:49:26,681] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Daily_img_transfer
AIRFLOW_CTX_TASK_ID=move_images
AIRFLOW_CTX_EXECUTION_DATE=2025-09-11T08:49:25.020713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-11T08:49:25.020713+00:00
[2025-09-11 08:49:26,682] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-11 08:49:26,683] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv C:/Users/maria/Desktop/dsl_ft_33/00_Projets_certif/bloc4/03_Jedha_aia_bloc_4_Final_project/wakee_lead/src/temp/*.jpg C:/Users/maria/Desktop/dsl_ft_33/00_Projets_certif/bloc4/03_Jedha_aia_bloc_4_Final_project/wakee_lead/data/raw_images/']
[2025-09-11 08:49:26,688] {subprocess.py:85} INFO - Output:
[2025-09-11 08:49:26,690] {subprocess.py:92} INFO - mv: cannot stat 'C:/Users/maria/Desktop/dsl_ft_33/00_Projets_certif/bloc4/03_Jedha_aia_bloc_4_Final_project/wakee_lead/src/temp/*.jpg': No such file or directory
[2025-09-11 08:49:26,691] {subprocess.py:96} INFO - Command exited with return code 1
[2025-09-11 08:49:26,701] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-11 08:49:26,704] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Daily_img_transfer, task_id=move_images, execution_date=20250911T084925, start_date=20250911T084926, end_date=20250911T084926
[2025-09-11 08:49:26,711] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 697)
[2025-09-11 08:49:26,734] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-11 08:49:26,760] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
