[2025-09-11T16:32:29.239+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-11T16:32:29.255+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T16:32:26.411618+00:00 [queued]>
[2025-09-11T16:32:29.262+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T16:32:26.411618+00:00 [queued]>
[2025-09-11T16:32:29.264+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-09-11T16:32:29.273+0000] {taskinstance.py:2907} INFO - Executing <Task(BashOperator): move_images> on 2025-09-11 16:32:26.411618+00:00
[2025-09-11T16:32:29.278+0000] {standard_task_runner.py:72} INFO - Started process 257 to run task
[2025-09-11T16:32:29.280+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-11T16:32:26.411618+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpullwuvs8']
[2025-09-11T16:32:29.281+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask move_images
[2025-09-11T16:32:29.312+0000] {task_command.py:467} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T16:32:26.411618+00:00 [running]> on host d403547ecef7
[2025-09-11T16:32:29.368+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Daily_img_transfer' AIRFLOW_CTX_TASK_ID='move_images' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T16:32:26.411618+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-11T16:32:26.411618+00:00'
[2025-09-11T16:32:29.370+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-11T16:32:29.379+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-11T16:32:29.381+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n                                pwd\n                                ls\n                                cd ../../opt/***\n                                pwd\n                                ls\n                                mv src/temp/*.jpg data/raw_images\n                                ']
[2025-09-11T16:32:29.388+0000] {subprocess.py:99} INFO - Output:
[2025-09-11T16:32:29.390+0000] {subprocess.py:106} INFO - /tmp/***tmp033ohheb
[2025-09-11T16:32:29.392+0000] {subprocess.py:106} INFO - /opt/***
[2025-09-11T16:32:29.393+0000] {subprocess.py:106} INFO - ***.cfg
[2025-09-11T16:32:29.394+0000] {subprocess.py:106} INFO - config
[2025-09-11T16:32:29.395+0000] {subprocess.py:106} INFO - dags
[2025-09-11T16:32:29.396+0000] {subprocess.py:106} INFO - data
[2025-09-11T16:32:29.396+0000] {subprocess.py:106} INFO - logs
[2025-09-11T16:32:29.397+0000] {subprocess.py:106} INFO - models
[2025-09-11T16:32:29.397+0000] {subprocess.py:106} INFO - plugins
[2025-09-11T16:32:29.398+0000] {subprocess.py:106} INFO - requirements.txt
[2025-09-11T16:32:29.399+0000] {subprocess.py:106} INFO - webserver_config.py
[2025-09-11T16:32:29.399+0000] {subprocess.py:106} INFO - mv: cannot stat 'src/temp/*.jpg': No such file or directory
[2025-09-11T16:32:29.400+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-09-11T16:32:29.408+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-11T16:32:29.413+0000] {taskinstance.py:1242} INFO - Marking task as FAILED. dag_id=Daily_img_transfer, task_id=move_images, run_id=manual__2025-09-11T16:32:26.411618+00:00, execution_date=20250911T163226, start_date=20250911T163229, end_date=20250911T163229
[2025-09-11T16:32:29.431+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-11T16:32:29.432+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 257)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-11T16:32:29.493+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-11T16:32:29.514+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-11T16:32:29.518+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
