[2025-09-12T10:06:26.816+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-12T10:06:26.837+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Daily_img_transfer.move_images manual__2025-09-12T10:06:25.020600+00:00 [queued]>
[2025-09-12T10:06:26.845+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Daily_img_transfer.move_images manual__2025-09-12T10:06:25.020600+00:00 [queued]>
[2025-09-12T10:06:26.847+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 2
[2025-09-12T10:06:26.858+0000] {taskinstance.py:2907} INFO - Executing <Task(BashOperator): move_images> on 2025-09-12 10:06:25.020600+00:00
[2025-09-12T10:06:26.864+0000] {standard_task_runner.py:72} INFO - Started process 233 to run task
[2025-09-12T10:06:26.867+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-12T10:06:25.020600+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp5z0zfvvf']
[2025-09-12T10:06:26.869+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask move_images
[2025-09-12T10:06:26.916+0000] {task_command.py:467} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-12T10:06:25.020600+00:00 [running]> on host 860d02b706ad
[2025-09-12T10:06:26.992+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Daily_img_transfer' AIRFLOW_CTX_TASK_ID='move_images' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T10:06:25.020600+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T10:06:25.020600+00:00'
[2025-09-12T10:06:26.994+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-12T10:06:27.005+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-12T10:06:27.007+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n                                pwd\n                                ls\n                                cd ../../opt/***\n                                pwd\n                                ls\n                                mv src/temp/*.jpg data/raw_images\n                                ']
[2025-09-12T10:06:27.019+0000] {subprocess.py:99} INFO - Output:
[2025-09-12T10:06:27.020+0000] {subprocess.py:106} INFO - /tmp/***tmp4w1esdmw
[2025-09-12T10:06:27.022+0000] {subprocess.py:106} INFO - /opt/***
[2025-09-12T10:06:27.024+0000] {subprocess.py:106} INFO - ***.cfg
[2025-09-12T10:06:27.025+0000] {subprocess.py:106} INFO - config
[2025-09-12T10:06:27.025+0000] {subprocess.py:106} INFO - dags
[2025-09-12T10:06:27.026+0000] {subprocess.py:106} INFO - data
[2025-09-12T10:06:27.027+0000] {subprocess.py:106} INFO - logs
[2025-09-12T10:06:27.028+0000] {subprocess.py:106} INFO - models
[2025-09-12T10:06:27.029+0000] {subprocess.py:106} INFO - plugins
[2025-09-12T10:06:27.029+0000] {subprocess.py:106} INFO - requirements.txt
[2025-09-12T10:06:27.030+0000] {subprocess.py:106} INFO - src
[2025-09-12T10:06:27.031+0000] {subprocess.py:106} INFO - webserver_config.py
[2025-09-12T10:06:27.032+0000] {subprocess.py:106} INFO - mv: cannot stat 'src/temp/*.jpg': No such file or directory
[2025-09-12T10:06:27.032+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-09-12T10:06:27.044+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-12T10:06:27.054+0000] {taskinstance.py:1242} INFO - Marking task as UP_FOR_RETRY. dag_id=Daily_img_transfer, task_id=move_images, run_id=manual__2025-09-12T10:06:25.020600+00:00, execution_date=20250912T100625, start_date=20250912T100626, end_date=20250912T100627
[2025-09-12T10:06:27.079+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-12T10:06:27.080+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 233)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-12T10:06:27.122+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-12T10:06:27.140+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T10:06:27.143+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
