[2025-09-10 15:56:39,743] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T15:56:37.808292+00:00 [queued]>
[2025-09-10 15:56:39,750] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T15:56:37.808292+00:00 [queued]>
[2025-09-10 15:56:39,750] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-10 15:56:39,751] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-09-10 15:56:39,751] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-10 15:56:39,760] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): move_images> on 2025-09-10 15:56:37.808292+00:00
[2025-09-10 15:56:39,763] {standard_task_runner.py:52} INFO - Started process 4069 to run task
[2025-09-10 15:56:39,765] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-10T15:56:37.808292+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpyouyvq30', '--error-file', '/tmp/tmpr46_40hy']
[2025-09-10 15:56:39,766] {standard_task_runner.py:80} INFO - Job 4: Subtask move_images
[2025-09-10 15:56:39,803] {task_command.py:370} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T15:56:37.808292+00:00 [running]> on host 17d4e251db5b
[2025-09-10 15:56:39,846] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Daily_img_transfer
AIRFLOW_CTX_TASK_ID=move_images
AIRFLOW_CTX_EXECUTION_DATE=2025-09-10T15:56:37.808292+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-10T15:56:37.808292+00:00
[2025-09-10 15:56:39,847] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-10 15:56:39,847] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv src/temp/*.jpg data/raw_images/']
[2025-09-10 15:56:39,854] {subprocess.py:85} INFO - Output:
[2025-09-10 15:56:39,859] {subprocess.py:92} INFO - mv: cannot stat 'src/temp/*.jpg': No such file or directory
[2025-09-10 15:56:39,860] {subprocess.py:96} INFO - Command exited with return code 1
[2025-09-10 15:56:39,869] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10 15:56:39,872] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Daily_img_transfer, task_id=move_images, execution_date=20250910T155637, start_date=20250910T155639, end_date=20250910T155639
[2025-09-10 15:56:39,880] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 4069)
[2025-09-10 15:56:39,897] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-10 15:56:39,923] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
