[2025-09-11 10:03:55,999] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T10:03:54.599468+00:00 [queued]>
[2025-09-11 10:03:56,006] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T10:03:54.599468+00:00 [queued]>
[2025-09-11 10:03:56,007] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 10:03:56,008] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-09-11 10:03:56,008] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 10:03:56,019] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): move_images> on 2025-09-11 10:03:54.599468+00:00
[2025-09-11 10:03:56,023] {standard_task_runner.py:52} INFO - Started process 979 to run task
[2025-09-11 10:03:56,025] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-11T10:03:54.599468+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp3_cf9zj4', '--error-file', '/tmp/tmptlx3wld0']
[2025-09-11 10:03:56,026] {standard_task_runner.py:80} INFO - Job 37: Subtask move_images
[2025-09-11 10:03:56,064] {task_command.py:370} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T10:03:54.599468+00:00 [running]> on host 225d5ec060dd
[2025-09-11 10:03:56,111] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Daily_img_transfer
AIRFLOW_CTX_TASK_ID=move_images
AIRFLOW_CTX_EXECUTION_DATE=2025-09-11T10:03:54.599468+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-11T10:03:54.599468+00:00
[2025-09-11 10:03:56,112] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-11 10:03:56,113] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv /src/temp /data/raw_images']
[2025-09-11 10:03:56,119] {subprocess.py:85} INFO - Output:
[2025-09-11 10:03:56,121] {subprocess.py:92} INFO - mv: cannot stat '/src/temp': No such file or directory
[2025-09-11 10:03:56,122] {subprocess.py:96} INFO - Command exited with return code 1
[2025-09-11 10:03:56,131] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-11 10:03:56,134] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Daily_img_transfer, task_id=move_images, execution_date=20250911T100354, start_date=20250911T100355, end_date=20250911T100356
[2025-09-11 10:03:56,141] {standard_task_runner.py:97} ERROR - Failed to execute job 37 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 979)
[2025-09-11 10:03:56,197] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-11 10:03:56,223] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
