[2025-09-10 15:57:56,467] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T15:57:54.979142+00:00 [queued]>
[2025-09-10 15:57:56,474] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T15:57:54.979142+00:00 [queued]>
[2025-09-10 15:57:56,475] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-10 15:57:56,475] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-09-10 15:57:56,476] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-10 15:57:56,486] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): move_images> on 2025-09-10 15:57:54.979142+00:00
[2025-09-10 15:57:56,490] {standard_task_runner.py:52} INFO - Started process 4138 to run task
[2025-09-10 15:57:56,492] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-10T15:57:54.979142+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpzv20fm5s', '--error-file', '/tmp/tmpqclbvjs4']
[2025-09-10 15:57:56,493] {standard_task_runner.py:80} INFO - Job 6: Subtask move_images
[2025-09-10 15:57:56,529] {task_command.py:370} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T15:57:54.979142+00:00 [running]> on host 17d4e251db5b
[2025-09-10 15:57:56,576] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Daily_img_transfer
AIRFLOW_CTX_TASK_ID=move_images
AIRFLOW_CTX_EXECUTION_DATE=2025-09-10T15:57:54.979142+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-10T15:57:54.979142+00:00
[2025-09-10 15:57:56,577] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-10 15:57:56,578] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv src/temp/*.jpg data/raw_images/']
[2025-09-10 15:57:56,584] {subprocess.py:85} INFO - Output:
[2025-09-10 15:57:56,586] {subprocess.py:92} INFO - mv: cannot stat 'src/temp/*.jpg': No such file or directory
[2025-09-10 15:57:56,587] {subprocess.py:96} INFO - Command exited with return code 1
[2025-09-10 15:57:56,597] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10 15:57:56,600] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Daily_img_transfer, task_id=move_images, execution_date=20250910T155754, start_date=20250910T155756, end_date=20250910T155756
[2025-09-10 15:57:56,608] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 4138)
[2025-09-10 15:57:56,626] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-10 15:57:56,653] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
