[2025-09-10 16:01:00,277] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T16:00:57.994151+00:00 [queued]>
[2025-09-10 16:01:00,286] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T16:00:57.994151+00:00 [queued]>
[2025-09-10 16:01:00,287] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-10 16:01:00,288] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-09-10 16:01:00,288] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-10 16:01:00,300] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): move_images> on 2025-09-10 16:00:57.994151+00:00
[2025-09-10 16:01:00,304] {standard_task_runner.py:52} INFO - Started process 98 to run task
[2025-09-10 16:01:00,307] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-10T16:00:57.994151+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpkdc6ff_k', '--error-file', '/tmp/tmp5r3d0ha1']
[2025-09-10 16:01:00,308] {standard_task_runner.py:80} INFO - Job 10: Subtask move_images
[2025-09-10 16:01:00,360] {task_command.py:370} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-10T16:00:57.994151+00:00 [running]> on host 17d4e251db5b
[2025-09-10 16:01:00,415] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Daily_img_transfer
AIRFLOW_CTX_TASK_ID=move_images
AIRFLOW_CTX_EXECUTION_DATE=2025-09-10T16:00:57.994151+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-10T16:00:57.994151+00:00
[2025-09-10 16:01:00,416] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-10 16:01:00,418] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv src/temp/*.jpg data/raw_images/']
[2025-09-10 16:01:00,425] {subprocess.py:85} INFO - Output:
[2025-09-10 16:01:00,428] {subprocess.py:92} INFO - mv: cannot stat 'src/temp/*.jpg': No such file or directory
[2025-09-10 16:01:00,428] {subprocess.py:96} INFO - Command exited with return code 1
[2025-09-10 16:01:00,440] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10 16:01:00,443] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Daily_img_transfer, task_id=move_images, execution_date=20250910T160057, start_date=20250910T160100, end_date=20250910T160100
[2025-09-10 16:01:00,454] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 98)
[2025-09-10 16:01:00,480] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-10 16:01:00,509] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
