[2025-09-11 08:47:01,110] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T08:46:59.163451+00:00 [queued]>
[2025-09-11 08:47:01,117] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T08:46:59.163451+00:00 [queued]>
[2025-09-11 08:47:01,118] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 08:47:01,118] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-09-11 08:47:01,119] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 08:47:01,130] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): move_images> on 2025-09-11 08:46:59.163451+00:00
[2025-09-11 08:47:01,133] {standard_task_runner.py:52} INFO - Started process 583 to run task
[2025-09-11 08:47:01,135] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-11T08:46:59.163451+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp1_jl_ai5', '--error-file', '/tmp/tmpkfd42shx']
[2025-09-11 08:47:01,136] {standard_task_runner.py:80} INFO - Job 21: Subtask move_images
[2025-09-11 08:47:01,175] {task_command.py:370} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T08:46:59.163451+00:00 [running]> on host 17d4e251db5b
[2025-09-11 08:47:01,222] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Daily_img_transfer
AIRFLOW_CTX_TASK_ID=move_images
AIRFLOW_CTX_EXECUTION_DATE=2025-09-11T08:46:59.163451+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-11T08:46:59.163451+00:00
[2025-09-11 08:47:01,222] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-11 08:47:01,223] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mv C:\\Users\\maria\\Desktop\\dsl_ft_33\\00_Projets_certif\\bloc4\\03_Jedha_aia_bloc_4_Final_project\\wakee_lead\\src\\temp\\*.jpg C:\\Users\\maria\\Desktop\\dsl_ft_33\\00_Projets_certif\\bloc4\\03_Jedha_aia_bloc_4_Final_project\\wakee_lead\\data\\raw_images']
[2025-09-11 08:47:01,229] {subprocess.py:85} INFO - Output:
[2025-09-11 08:47:01,231] {subprocess.py:92} INFO - mv: cannot stat 'C:UsersmariaDesktopdsl_ft_3300_Projets_certifbloc403_Jedha_aia_bloc_4_Final_projectwakee_leadsrctemp*.jpg': No such file or directory
[2025-09-11 08:47:01,231] {subprocess.py:96} INFO - Command exited with return code 1
[2025-09-11 08:47:01,240] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-11 08:47:01,243] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Daily_img_transfer, task_id=move_images, execution_date=20250911T084659, start_date=20250911T084701, end_date=20250911T084701
[2025-09-11 08:47:01,251] {standard_task_runner.py:97} ERROR - Failed to execute job 21 for task move_images (Bash command failed. The command returned a non-zero exit code 1.; 583)
[2025-09-11 08:47:01,267] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-11 08:47:01,294] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
